baseURL = "https://quasar.codes"
languageCode = "en-us"
title = "Quasar"
pagination.pagerSize = 5 #frontpage pagination

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]

