name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Build hugo page
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_0.49.2_Linux-64bit.deb
          sudo dpkg -i hugo*.deb
          rm -rf public 2> /dev/null
          rm *.deb

      - name: Build conda index
        run: |
          conda install conda-build
          cd static/conda
          conda index
          cd ../..

      - name: Build page
        run: |
          hugo
          echo 'quasar.codes' > public/CNAME
          touch public/.nojekyll

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
