name: Push to GitHub Pages on push to master
on:
  schedule:
    # every day at midnight: https://crontab.guru/every-midnight
    - cron:  '0 0 * * *'

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        
      - name: Build hugo page
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_0.145.0_Linux-amd64.deb
          sudo dpkg -i hugo*.deb
          rm -rf public 2> /dev/null
          rm *.deb

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Disabled for now due to spurious timeouts
      #- name: Refresh citations
      #  run: |
      #    pip install https://github.com/scholarly-python-package/scholarly/archive/refs/heads/main.zip
      #    pip install toml
      #    python scripts/update_citations.py

      - name: Build conda index
        run: |
          conda install conda-build
          cd static/conda
          conda index .
          cd ../..

      - name: Build page
        run: |
          hugo
          echo 'quasar.codes' > public/CNAME
          touch public/.nojekyll

      # Deploy to local repo
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          SQUASH_HISTORY: True
          SKIP_EMPTY_COMMITS: True
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--verbose --no-progress './public/**/*.html'"
          fail: true
